# Generated by Django 3.2.7 on 2022-01-28 08:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr'), ('PROF', 'Prof'), ('ENG', 'Eng'), ('HON', 'Hon')], max_length=6)),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('pick_up_Location', models.CharField(max_length=100)),
                ('drop_off_Location', models.CharField(max_length=100)),
                ('pick_up_time', models.DateField(blank=True, null=True)),
                ('drop_off_time', models.DateField(blank=True, null=True)),
                ('bookedOn', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'View Bookings sent via website',
                'ordering': ('pick_up_time',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr'), ('PROF', 'Prof'), ('ENG', 'Eng'), ('HON', 'Hon')], max_length=6)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('createdAt', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers list',
            },
        ),
        migrations.CreateModel(
            name='CustomersMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Customers Message Sent via website',
            },
        ),
        migrations.CreateModel(
            name='OurFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Our Fleet',
            },
        ),
    ]
